[extension]
name = "Dolly Zoom Setup"
blender_version = "3.3"
version = "1.0.0"
author = "dura.xyz"
description = "Adds simple dolly zoom camera setup with automatic driver configuration."
category = "Camera"
support = "COMMUNITY"
license = "GPL-3.0"
doc_url = "https://github.com/duraxyz/dolly-zoom-setup"
tracker_url = "https://github.com/duraxyz/dolly-zoom-setup/issues"
